apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground
  namespace: dev
spec:
  selector:
    matchLabels:
      app: playground
  replicas: 1
  template:
    metadata:
      labels:
        app: playground
    spec:
      containers:
      - name: playground
        image: wil42/playground:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: playground-service
  namespace: dev
spec:
  selector:
    app: playground
  ports:
  - port: 8888
    name: http
    targetPort: 8888
  type: ClusterIP

